name: Flutter CI

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    paths:
      - "gen/**"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - "pubspec.lock"
  pull_request:
    branches: ["*"]
    paths:
      - "gen/**"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
      - "pubspec.lock"

jobs:
  build:
    name: Check any issues
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter SDK
        uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: latest
          cache: true
          cache-sdk: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Get Flutter dependencies on gen
        run: flutter pub get
        working-directory: gen

      - name: Check for any formatting issues in the code
        run: dart format --set-exit-if-changed . gen

      - name: Statically analyze the Dart code for any errors
        run: dart analyze . gen

      - name: Run widget tests for our Flutter project.
        run: flutter test
