name: Run gen script

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC

jobs:
  gen:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies 
        run: dart pub get
        working-directory: gen
      
      - name: Run gen/main.dart
        run: dart run main.dart
        working-directory: gen

      - name: Get current date
        id: date
        run: |
          echo "MONTH_YEAR=$(date +'%B %Y')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: "feat: add identifiers for ${{ steps.date.outputs.MONTH_YEAR }} models"
          commit-message: "feat: add identifiers for ${{ steps.date.outputs.MONTH_YEAR }} models"
          branch: gen
